version: '3'
services:
  db:
    image: mysql:5.7 # Change to your preferred MySQL version
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_DATABASE: LAU_Event_App
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - "3307:3306" # Change the first port number if you want to map to a different host port
